* File: inv2.pex.netlist.INV2.pxi
* Created: Fri Oct  4 15:57:17 2019
* 
x_PM_INV2_GROUND N_GROUND_M0_s N_GROUND_M0_b GROUND PM_INV2_GROUND
x_PM_INV2_VOUT N_VOUT_M0_d N_VOUT_M1_d VOUT PM_INV2_VOUT
x_PM_INV2_VDD N_VDD_M1_b N_VDD_M1_s VDD PM_INV2_VDD
x_PM_INV2_VIN N_VIN_M0_g N_VIN_M1_g VIN PM_INV2_VIN
